[VCDA-4776] Fix to ensure EnsureLoadBalancerDeleted is called for failed loadbalancer creations
vmware/cloud-provider-for-cloud-director pull request #166
Opened 2022-11-04 19:19 UTC by lzichong

* Ensure clean up of VCD resources even if loadbalancer fails to come up completely
* Tested with:
  * CSE 3.1.3 cluster - Install Ingress using helm without specifying any cert annotations and then deleting the service with helm uninstall
  * CSE 3.1.3 cluster - Install Ingress using helm and specifying invalid certificate and then deleting the service with helm uninstall
  * CSE 3.1.3 cluster - Install Ingress using helm and loadbalancer came up successfully, performed helm uninstall and cleanly deleted everything

Signed-off-by: lzichong <lzichong@vmware.com>

2022-11-07 23:27 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-:-NGJPlopCRxX5t0xNsVW:bg7igkv)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @arunmk and @lzichong)

___
*[`pkg/vcdclient/gateway.go` line 1744 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGJNClF2TuDWn5RkXcZ:-NGJNClG4RgTpgQXWfRw:bo8ax3k) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/28dc12afcf5ec7b07f1f668578d61484e90f1b5c/pkg/vcdclient/gateway.go#L1744)):*
> ```Go
> }
> 
> func (client *Client) HasVCDResources(ctx context.Context, virtualServiceNamePrefix string,
> ```

Can we change the name of the function to indicate that we are checking if VCDResources for Application LB is present.
Something like `VerifyVCDResourcesForApplicaitonLB`


<!-- Sent from Reviewable.io -->

2022-11-08 00:46 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdclient/gateway.go` line 1744 at r3](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGJNClF2TuDWn5RkXcZ:-NGJgxjl4KcxxvXJuAyF:bvpr1mz) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/28dc12afcf5ec7b07f1f668578d61484e90f1b5c/pkg/vcdclient/gateway.go#L1744)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we change the name of the function to indicate that we are checking if VCDResources for Application LB is present.
Something like `VerifyVCDResourcesForApplicaitonLB`
</blockquote></details>

Updated, thanks Aniruddh!


<!-- Sent from Reviewable.io -->

2022-11-08 19:59 UTC, arunmk requested changes
There are a few important changes needed. Apart from this I am ot seeing changed in GetLoadBalancer. Does that remain unchaged?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-:-NGNoqo_AH6KIU6N31HI:b-kl14z0)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @lzichong)

___
*[`pkg/ccm/loadbalancer.go` line 199 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGNo3Vz6q47x5uwYr7o:-NGNo3Vz6q47x5uwYr7p:bbd84me) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dbf5d76ca066f06f4d35e5a764a5e08239e34876/pkg/ccm/loadbalancer.go#L199)):*
> ```Go
> 	// In this case, we would need to check if there is any VCD resources, if so we can return true for 'exists' to controller to call EnsureLoadBalancerDeleted()
> 	if !lbExists {
> 		hasVcdResources, vcdResourceCheckErr := lb.verifyVCDResourcesForAppliationLB(ctx, service)
> ```

typo: Appliation
___
*[`pkg/vcdclient/gateway.go` line 1775 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGNokbH-h7gcjHaq4LB:-NGNokbH-h7gcjHaq4LC:b-yermam) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dbf5d76ca066f06f4d35e5a764a5e08239e34876/pkg/vcdclient/gateway.go#L1775)):*
> ```Go
> 		}
> 
> 		dnatRuleRef, err := client.getNATRuleRef(ctx, dnatRuleName)
> ```

This can be optional and you need to check if the shared IP mode is allowed.


<!-- Sent from Reviewable.io -->

2022-11-08 20:10 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/ccm/loadbalancer.go` line 199 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGNo3Vz6q47x5uwYr7o:-NGNrFW48FqhXz82-6Y2:b-k5zjvr) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dbf5d76ca066f06f4d35e5a764a5e08239e34876/pkg/ccm/loadbalancer.go#L199)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

typo: Appliation
</blockquote></details>

Updated, thanks for the catch!
___
*[`pkg/vcdclient/gateway.go` line 1775 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGNokbH-h7gcjHaq4LB:-NGNqKrr3_jXpC18xDzP:b-22x1l5) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dbf5d76ca066f06f4d35e5a764a5e08239e34876/pkg/vcdclient/gateway.go#L1775)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This can be optional and you need to check if the shared IP mode is allowed.
</blockquote></details>

By optional, is this referring to OneArm being nil? For CPI 1.1.x, I couldn't find the `enableVirtualServiceSharedIP` in the ConfigMap as opposed to it being in CPI 1.2, this isn't supported for CPI 1.1.x right? 


<!-- Sent from Reviewable.io -->

2022-11-08 20:14 UTC, lzichong commented
> There are a few important changes needed. Apart from this I am ot seeing changed in GetLoadBalancer. Does that remain unchaged?
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-:-NGNoqo_AH6KIU6N31HI:b-kl14z0)_ status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @lzichong)
> 
> _[`pkg/ccm/loadbalancer.go` line 199 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGNo3Vz6q47x5uwYr7o:-NGNo3Vz6q47x5uwYr7p:bbd84me) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dbf5d76ca066f06f4d35e5a764a5e08239e34876/pkg/ccm/loadbalancer.go#L199)):_
> 
> > ```go
> > 	// In this case, we would need to check if there is any VCD resources, if so we can return true for 'exists' to controller to call EnsureLoadBalancerDeleted()
> > 	if !lbExists {
> > 		hasVcdResources, vcdResourceCheckErr := lb.verifyVCDResourcesForAppliationLB(ctx, service)
> > ```
> 
> typo: Appliation
> 
> _[`pkg/vcdclient/gateway.go` line 1775 at r5](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-NGNokbH-h7gcjHaq4LB:-NGNokbH-h7gcjHaq4LC:b-yermam) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/dbf5d76ca066f06f4d35e5a764a5e08239e34876/pkg/vcdclient/gateway.go#L1775)):_
> 
> > ```go
> > 		}
> > 
> > 		dnatRuleRef, err := client.getNATRuleRef(ctx, dnatRuleName)
> > ```
> 
> This can be optional and you need to check if the shared IP mode is allowed.

Yes, this was all the changes needed for `GetLoadBalancer()` that gets called by the controller to validate if it should call `EnsureDeleteLoadBalancer()` as long as load balancer did not fully come up and there were some resources that was created. In terms of the actual core logic of `vcdClient.getLoadbalancer()`, I think it is probably better for us not to directly modify it too much as it does return as expected, or do you think we need to modify the core logic?

2022-11-10 01:05 UTC, arunmk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/166#-:-NGU3YLxAaj32TPBMIJf:bg7igkv)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2022-11-10 19:36 UTC, merged