[VKCI-90] common code for Kubernetes CRUD operation
vmware/cloud-provider-for-cloud-director pull request #183
Opened 2022-12-08 22:59 UTC by ymo24

* common code for Kubernetes CRUD operation

Signed-off-by: ymo24 <ymo@vmware.com>

2022-12-08 23:23 UTC, lzichong requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @arunmk, @rliang88, and @ymo24)

___
*[`pkg/Testingsdk/k8sclient.go` line 21 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-flxEd-Ku0hG1d7x:-NIo-flxEd-Ku0hG1d7y:b-ij5mrb) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L21)):*
> ```Go
> )
> 
> var (
> ```

nit: const



_Code quote:_
```Go
var
```
___
*[`pkg/Testingsdk/k8sclient.go` line 24 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo1DGy1wmIE-6giZj8:-NIo1DGy1wmIE-6giZj9:bqo1t4f) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L24)):*
> ```Go
> 	ResourceExisted   = errors.New("[REX] resource is already existed")
> 	ResourceNotFound  = errors.New("[RNF] resource is not found")
> 	ResourceNameNulll = errors.New("[RNN] resource name is null")
> ```

typo: ResourceNameNull



_Code quote:_
```Go
ResourceNameNulll
```
___
*[`pkg/Testingsdk/k8sclient.go` line 34 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-V2g1ID3K0cTaYkM:-NIo-V2g1ID3K0cTaYkN:b63md1f) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L34)):*
> ```Go
> 		pvc, err := getPVC(ctx, k8sClient, nameSpace, pvcName)
> 		if err != nil {
> 			if apierrs.IsInternalError(err) || apierrs.IsTimeout(err) || apierrs.IsServerTimeout(err) ||
> ```

Could we move all usage of this check into a function called `IsRetryableError(err) bool`?



_Code quote:_
```Go
			if apierrs.IsInternalError(err) || apierrs.IsTimeout(err) || apierrs.IsServerTimeout(err) ||
				apierrs.IsTooManyRequests(err) || utilnet.IsProbableEOF(err) || utilnet.IsConnectionReset(err) {
				return false, nil
			}
```
___
*[`pkg/Testingsdk/k8sclient.go` line 43 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo07Ig6CA0-Tx4U21z:-NIo07Ig6CA0-Tx4U22-:bwkepbc) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L43)):*
> ```Go
> 			return false, nil
> 		}
> 		if pvc != nil && pvc.Status.Phase == "Bound" {
> ```

Is there a apiv1 constant for this similar to `apiv1.PodRunning`?



_Code quote:_
```Go
"Bound"
```
___
*[`pkg/Testingsdk/k8sclient.go` line 60 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-y6-9RIFm52hFkk8:-NIo-y6-9RIFm52hFkk9:b-othm7e) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L60)):*
> ```Go
> func isDeploymentReady(ctx context.Context, k8sClient *kubernetes.Clientset, nameSpace string, deployName string) (bool, error) {
> 	retryInterval := 20 * time.Second
> 	retryTimeout := 140 * time.Second
> ```

Can we move these to as constants? `defaultRetryInterval` and `defaultRetryTimeout`?



_Code quote:_
```Go
	retryInterval := 20 * time.Second
	retryTimeout := 140 * time.Second
```
___
*[`pkg/Testingsdk/k8sclient.go` line 189 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo0j8bDhig1hm3tYZ0:-NIo0j8bDhig1hm3tYZ1:bfn72k8) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L189)):*
> ```Go
> 		_, err := k8sClient.CoreV1().Namespaces().Get(ctx, nameSpace, metav1.GetOptions{})
> 		if err != nil {
> 			if err.(*apierrs.StatusError).ErrStatus.Reason == "NotFound" {
> ```

Can we use use an apierrs here, with `apierrs.IsNotFound(err)` instead of checking by "NotFound"? Similar to all the other areas where we are using this check



_Code quote:_
```Go
			if err.(*apierrs.StatusError).ErrStatus.Reason == "NotFound" {
				return true, nil
			}
```
___
*[`pkg/Testingsdk/k8sclient.go` line 243 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo12EC77DJqlcMOMIF:-NIo12EC77DJqlcMOMIG:b48k95r) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L243)):*
> ```Go
> }
> 
> func getPodByPrefix(ctx context.Context, k8sClient *kubernetes.Clientset, nameSpace string, podNamePrefix string) ([]*apiv1.Pod, error) {
> ```

nit: getPodsByPrefix as we are returning a list of pods



_Code quote:_
```Go
getPodByPrefix
```
___
*[`pkg/Testingsdk/client.go` line 1 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-9Oq45bLSfJLaGAc:-NIo-9Oq45bLSfJLaGAd:bknpmsn) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/client.go#L1)):*
> ```Go
> package Testingsdk
> ```

Can we replace this to `testingsdk` with lowercase to keep same style as the others?


<!-- Sent from Reviewable.io -->

2022-12-09 21:03 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @arunmk, @lzichong, and @rliang88)

___
*[`pkg/Testingsdk/client.go` line 1 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-9Oq45bLSfJLaGAc:-NIs_bxl0JdLhKpHmMqv:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/client.go#L1)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Can we replace this to `testingsdk` with lowercase to keep same style as the others?
</blockquote></details>

Done.
___
*[`pkg/Testingsdk/k8sclient.go` line 34 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-V2g1ID3K0cTaYkM:-NIs_ja40THVSTqYYtr2:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L34)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Could we move all usage of this check into a function called `IsRetryableError(err) bool`?
</blockquote></details>

Done.



_Code quote:_
```Go
apierrs.IsTooManyRequests(err) || utilnet.IsProbableEOF(err)
```
___
*[`pkg/Testingsdk/k8sclient.go` line 43 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo07Ig6CA0-Tx4U21z:-NIs_fIWCgjRuP48HNg2:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L43)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Is there a apiv1 constant for this similar to `apiv1.PodRunning`?
</blockquote></details>

Done.
___
*[`pkg/Testingsdk/k8sclient.go` line 189 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo0j8bDhig1hm3tYZ0:-NIs_YKv4sXkSqVfM_US:brxg4wi) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L189)):*
> "NotFound"
Already updated, thanks Zichong


<!-- Sent from Reviewable.io -->

2022-12-09 21:03 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @arunmk, @lzichong, and @rliang88)

___
*[`pkg/Testingsdk/k8sclient.go` line 21 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-flxEd-Ku0hG1d7x:-NIsgmZLA3n-4axBrYF7:b7qk8hq) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L21)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

nit: const
</blockquote></details>

We can keep error as var. Thanks Zichong
___
*[`pkg/Testingsdk/k8sclient.go` line 60 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIo-y6-9RIFm52hFkk8:-NIsgrKRB1n-ovoeRS2Q:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L60)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Can we move these to as constants? `defaultRetryInterval` and `defaultRetryTimeout`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 21:08 UTC, lzichong approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @arunmk and @rliang88)



<!-- Sent from Reviewable.io -->

2022-12-12 23:19 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @arunmk, @rliang88, and @ymo24)

___
*[`pkg/testingsdk/client.go` line 276 at r4](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7cZCCE_eLRTnsKqx2:-NJ7cZCCE_eLRTnsKqx3:b-epnp6x) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/cb9c8c110e6067cc333a34cf0570e39b662b437a/pkg/testingsdk/client.go#L276)):*
> ```Go
> }
> 
> func (tc *TestClient) IsWorkerNodeNotReady(ctx context.Context, workerNode *apiv1.Node) error {
> ```

Thanks for implementing this! Could you also add a comment why we can't use negate result from `IsWorkerNodeReady()`?



_Code quote:_
```Go
func (tc *TestClient) IsWorkerNodeNotReady(ctx context.Context, workerNode *apiv1.Node) error {
```


<!-- Sent from Reviewable.io -->

2022-12-12 23:21 UTC, rliang88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @arunmk, @lzichong, and @ymo24)

___
*[`pkg/Testingsdk/k8sclient.go` line 24 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7cuBQAgsIgJmorq8U:-NJ7cuBQAgsIgJmorq8V:b-4154i2) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L24)):*
> ```Go
> 	ResourceExisted   = errors.New("[REX] resource is already existed")
> 	ResourceNotFound  = errors.New("[RNF] resource is not found")
> 	ResourceNameNulll = errors.New("[RNN] resource name is null")
> ```

3 l's in this variable name, is this intentional?


<!-- Sent from Reviewable.io -->

2022-12-12 23:23 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @arunmk, @lzichong, and @rliang88)

___
*[`pkg/Testingsdk/k8sclient.go` line 24 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7cuBQAgsIgJmorq8U:-NJ7dY96707mJ6_5-YLc:bhof8fn) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L24)):*
<details><summary><i>Previously, rliang88 (Richard Liang) wrote…</i></summary><blockquote>

3 l's in this variable name, is this intentional?
</blockquote></details>

Are you looking at the latest version?


<!-- Sent from Reviewable.io -->

2022-12-12 23:27 UTC, rliang88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @arunmk, @lzichong, and @ymo24)

___
*[`pkg/Testingsdk/k8sclient.go` line 24 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7cuBQAgsIgJmorq8U:-NJ7eJ-u75viTxtN-epD:bemrzxu) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/8243531b99fdf5c4c89a676a419340e956d83518/pkg/Testingsdk/k8sclient.go#L24)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Are you looking at the latest version?
</blockquote></details>

oh good, it changed


<!-- Sent from Reviewable.io -->

2022-12-12 23:28 UTC, rliang88 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-:-NJ7el5pEqB3H-_uXlNp:bnfp4nl)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @arunmk, @lzichong, and @ymo24)



<!-- Sent from Reviewable.io -->

2022-12-13 18:37 UTC, lzichong approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-:-NJBl_lo-HBKmh-HIkFd:bnfp4nl)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @arunmk and @ymo24)



<!-- Sent from Reviewable.io -->

2023-01-11 08:40 UTC, arunmk approved these changes
After the changes mentioned it should be good to go.

2023-01-11 08:40 UTC, arunmk commented on pkg/testingsdk/client.go
> +		return nil, fmt.Errorf("error creating Persistent Volume [%s] for cluster [%s]: [%v]", persistentVolumeName, tc.ClusterId, err)
clusterName would be more helpful in these logs while debugging

2023-01-11 08:40 UTC, arunmk commented on pkg/testingsdk/client.go
> +	err := wait.PollImmediate(defaultNodeInterval, defaultNodeReadyTimeout, func() (bool, error) {
nice!

2023-01-11 08:40 UTC, arunmk commented on pkg/testingsdk/k8sclient.go
> +func isPvcReady(ctx context.Context, k8sClient *kubernetes.Clientset, nameSpace string, pvcName string) error {
this is actually a `waitForPvcReady`, correct?

2023-01-11 08:40 UTC, arunmk commented on pkg/testingsdk/k8sclient.go
> +func isDeploymentReady(ctx context.Context, k8sClient *kubernetes.Clientset, nameSpace string, deployName string) error {
same: this is also a `waitFor....`

I believe the other ones with the PollImmediate are also like that

2023-01-11 08:40 UTC, arunmk commented on pkg/testingsdk/k8sclient.go
> +		pods, err := getPodsByPrefix(ctx, k8sClient, nameSpace, deployName)
Here we need the pods of a deployment, correct? Those can be done in a different way: https://stackoverflow.com/questions/63142663/using-client-go-api-to-list-pods-managed-by-a-deployment-controller-not-working

2023-01-11 19:46 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 1 of 4 files reviewed, 13 unresolved discussions (waiting on @arunmk, @lzichong, and @rliang88)

___
*[`pkg/testingsdk/client.go` line 53 at r4](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7cL3sD6C-B3WEqtu5:-NLX8wvc11mBB3OOALlS:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/cb9c8c110e6067cc333a34cf0570e39b662b437a/pkg/testingsdk/client.go#L53)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Can you replace the codes that doesn't compile due to missing functions/files as TODO for now? This way it doesn't interfere with compiling when others are pulling in the code and submitting their PRs
</blockquote></details>

Done.
___
*[`pkg/testingsdk/client.go` line 68 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7_6EswYUlwIP9nlAc-r6-68:-NLXMOlvDQXAZ9Igxj-w:b7kw0jq) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d3be005523816078dd758e2249d9c2be648b11ff/pkg/testingsdk/client.go#L68)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

clusterName would be more helpful in these logs while debugging
</blockquote></details>

Thanks Arun, I have added ClusterName to every log
___
*[`pkg/testingsdk/client.go` line 141 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NJ7_6EswYUlwIP9nlAc-r6-141:-NLXMSwZEKcNZf8yccBh:b-u8fs2u) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d3be005523816078dd758e2249d9c2be648b11ff/pkg/testingsdk/client.go#L141)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

error string should be fixed
</blockquote></details>

Thanks Arun, already done
___
*[`pkg/testingsdk/k8sclient.go` line 36 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIsgS3FNXKOGlMd8a4O-r6-36:-NLXMViVAh2Q1_Avq4X7:b-u8fs2u) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d3be005523816078dd758e2249d9c2be648b11ff/pkg/testingsdk/k8sclient.go#L36)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

this is actually a `waitForPvcReady`, correct?
</blockquote></details>

Thanks Arun, already done
___
*[`pkg/testingsdk/k8sclient.go` line 61 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIsgS3FNXKOGlMd8a4O-r6-61:-NLXMY0VBwpBK7mt_HNE:b-896fix) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d3be005523816078dd758e2249d9c2be648b11ff/pkg/testingsdk/k8sclient.go#L61)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

same: this is also a `waitFor....`

I believe the other ones with the PollImmediate are also like that
</blockquote></details>

Done.
___
*[`pkg/testingsdk/k8sclient.go` line 63 at r6](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183#-NIsgS3FNXKOGlMd8a4O-r6-63:-NLXMYPA68IUKK4GOo5o:b-m1qis) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/d3be005523816078dd758e2249d9c2be648b11ff/pkg/testingsdk/k8sclient.go#L63)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Here we need the pods of a deployment, correct? Those can be done in a different way: https://stackoverflow.com/questions/63142663/using-client-go-api-to-list-pods-managed-by-a-deployment-controller-not-working
</blockquote></details>

Thanks Arun. I have already fixed it by using labelSelector


<!-- Sent from Reviewable.io -->

2023-01-11 19:56 UTC, lzichong approved these changes
> Reviewed 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/183)* status: 2 of 4 files reviewed, 13 unresolved discussions (waiting on @arunmk)



<!-- Sent from Reviewable.io -->

2023-01-11 20:06 UTC, merged