[VCDA-3513] Handle trailing slashes to avoid broken API paths
vmware/cloud-provider-for-cloud-director pull request #63
Opened 2022-04-05 22:11 UTC by lzichong

Ticket: VCDA-3513

- Updated cloudConfig to trim trailing slashes from host after parsing the config

2022-04-07 03:23 UTC, ltimothy7 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @lzichong)

___
*[pkg/config/cloudconfig.go, line 101 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63#-N-11vq_DFVqojkMaCTM:-N-11vq_DFVqojkMaCTN:bv3dlz5) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/ab9d230589f8cbe8d97b5f7b44a0fbea8fb4a0e7/pkg/config/cloudconfig.go#L101)):*
> ```Go
> 		return nil, fmt.Errorf("unable to decode yaml file: [%v]", err)
> 	}
> 	trimSlashFromHost(config)
> ```

I think it would be clearer if you make the function call here instead of passing the entire config to a helper function.

You can just do:
`cloudConfig.VCD.Host = strings.TrimRight(cloudConfig.VCD.Host, "/")`

here


<!-- Sent from Reviewable.io -->

2022-04-07 18:39 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[pkg/config/cloudconfig.go, line 101 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63#-N-11vq_DFVqojkMaCTM:-N-4JlDH4TdYyMptAExL:bkcaj5i) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/ab9d230589f8cbe8d97b5f7b44a0fbea8fb4a0e7/pkg/config/cloudconfig.go#L101)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think it would be clearer if you make the function call here instead of passing the entire config to a helper function.

You can just do:
`cloudConfig.VCD.Host = strings.TrimRight(cloudConfig.VCD.Host, "/")`

here

</blockquote></details>

Updated, thanks Tim!


<!-- Sent from Reviewable.io -->

2022-04-07 20:58 UTC, ltimothy7 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63#-:-N-4oelC4mlg0U93HaXv:bg7igkv)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)



<!-- Sent from Reviewable.io -->

2022-04-08 16:33 UTC, arunmk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63#-:-N-90SUF9VYMQP6PHTAk:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arunmk and @ltimothy7)



<!-- Sent from Reviewable.io -->

2022-04-08 20:26 UTC, merged