VCDA 3630: Update NewVCDClientFromSecrets() to determine userOrg from username
vmware/cloud-provider-for-cloud-director pull request #68
Opened 2022-04-28 23:43 UTC by lzichong

* Updated the `client.go` to handle `system/administrator` as `userOrg: system`, `user: administrator`
* This has the same implementation as CAPVCD 0.5.x, and it was working for CAPVCD 0.5.x
* Testings:
  - Built new image, deleted old deployment/configmap,  old TKGm cluster was still running fine after updating CPI image/deployment

2022-04-28 23:51 UTC, arunmk requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @lzichong, and @sahithi)

___
*[`pkg/vcdsdk/client.go` line 107 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68#-N0m_LxA5H3P6SH2Hguf:-N0m_LxA5H3P6SH2Hgug:b9a4nzp) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6c4aea64fc8184340347448a2611e2f1c0df2cf2/pkg/vcdsdk/client.go#L107)):*
> ```Go
> 	// TODO: validation of parameters
> 
> 	newUserOrg, newUsername, err := config.GetUserAndOrg(user, userOrg)
> ```

This should pass clusterOrg and not userOrg, correct?


<!-- Sent from Reviewable.io -->

2022-04-29 00:02 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/vcdsdk/client.go` line 107 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68#-N0m_LxA5H3P6SH2Hguf:-N0mbHxm4ivpn5zfvan1:b-uycznu) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6c4aea64fc8184340347448a2611e2f1c0df2cf2/pkg/vcdsdk/client.go#L107)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should pass clusterOrg and not userOrg, correct?
</blockquote></details>

Actually yes I think that is the correct way to call the function. I passed in userOrg as by default it is the same value as org and in CAPVCD controllers we were passing in ClusterSpec.Org in userOrg param to create client. I will update this to orgName, thanks Arun!


<!-- Sent from Reviewable.io -->

2022-04-29 00:06 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/vcdsdk/client.go` line 107 at r1](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68#-N0m_LxA5H3P6SH2Hguf:-N0mcNSu8YNpTYJobCYw:br3lqyd) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/6c4aea64fc8184340347448a2611e2f1c0df2cf2/pkg/vcdsdk/client.go#L107)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Actually yes I think that is the correct way to call the function. I passed in userOrg as by default it is the same value as org and in CAPVCD controllers we were passing in ClusterSpec.Org in userOrg param to create client. I will update this to orgName, thanks Arun!
</blockquote></details>

Can we actually remove userOrg param from NewVCDClientFromSecrets() in a new ticket? Since we are using orgName and full username to determine the userOrg and eventually pass that to create authConfig, the userOrg param will not be used at all.


<!-- Sent from Reviewable.io -->

2022-05-05 23:14 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Minor comment

> Reviewed 1 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68#-:-N1LV7iO8phYRd2Dn-nU:by0nmqt)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk, @lzichong, and @sahithi)

___
*[`pkg/vcdsdk/client.go` line 11 at r2](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68#-N0rTW288LLTAmjrpZo2:-N0rTW294Q9VKSmWl5m-:b-fffo68) ([raw file](https://github.com/vmware/cloud-provider-for-cloud-director/blob/b7aef23801c1e65df6fda8d3b279770237ae1d74/pkg/vcdsdk/client.go#L11)):*
> ```Go
> 	"crypto/tls"
> 	"fmt"
> 	"github.com/vmware/cloud-provider-for-cloud-director/pkg/config"
> ```

we should avoid making dependencies with other CPI packages in "vcdsdk" package.
Can you move the GetUserAndOrg function to the common library and have cloudconfig.go refer to vcdsdk?


<!-- Sent from Reviewable.io -->

2022-05-06 22:58 UTC, arunmk approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/68)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @lzichong, and @sahithi)



<!-- Sent from Reviewable.io -->

2022-05-06 23:01 UTC, merged